# version: 2023-11-05
# config for "data_preprocess_tmp" script

selected_group_features:
  - 'input_group_software_id'
  - 'input_group_description'
selected_technique_features:
  - 'input_technique_data_sources'
  - 'input_technique_defenses_bypassed'
  - 'input_technique_detection_name'
  - 'input_technique_mitigation_id'
  - 'input_technique_permissions_required'
  - 'input_technique_platforms'
  - 'input_technique_software_id'
  - 'input_technique_tactics'
  - 'input_technique_description'
include_unused_techniques: False
### limit feature cardinality
limit_technique_features: ~

limit_group_features: ~