SCRIPT_LOGS_FILENAME = 'script_logs.txt'

GROUP_ID_NAME = 'group_ID'
TECHNIQUE_ID_NAME = 'technique_ID'
LABEL_NAME = 'label'

INPUT_GROUP_LAYER_NAME = 'input_group'
INPUT_TECHNIQUE_LAYER_NAME = 'input_technique'

TRAIN_DATASET_FILENAME = 'train_dataset'
TRAIN_CV_DATASET_FILENAME = 'train_cv_dataset'
CV_DATASET_FILENAME = 'cv_dataset'
TEST_DATASET_FILENAME = 'test_dataset'

RANDOM_STATE = 13

"""
updated constants for feature names, used in:
data.cleaning_3
model1.modelpreprocess.build_dataset_2
"""
INPUT_GROUP_SOFTWARE_ID = 'input_group_software_id'
INPUT_GROUP_TACTICS = 'input_group_tactics'
INPUT_GROUP_INTERACTION_RATE = 'input_group_interaction_rate'
INPUT_GROUP_DESCRIPTION = 'input_group_description'

INPUT_TECHNIQUE_DATA_SOURCES = 'input_technique_data_sources'
INPUT_TECHNIQUE_DEFENSES_BYPASSED = 'input_technique_defenses_bypassed'
INPUT_TECHNIQUE_DETECTION_NAME = 'input_technique_detection_name'
INPUT_TECHNIQUE_MITIGATION_ID = 'input_technique_mitigation_id'
INPUT_TECHNIQUE_PERMISSIONS_REQUIRED = 'input_technique_permissions_required'
INPUT_TECHNIQUE_PLATFORMS = 'input_technique_platforms'
INPUT_TECHNIQUE_SOFTWARE_ID = 'input_technique_software_id'
INPUT_TECHNIQUE_TACTICS = 'input_technique_tactics'
INPUT_TECHNIQUE_DESCRIPTION = 'input_technique_description'
INPUT_TECHNIQUE_INTERACTION_RATE = 'input_technique_interaction_rate'

RAGGED_GROUP_FEATURES = [INPUT_GROUP_SOFTWARE_ID, INPUT_GROUP_TACTICS]
SCALAR_GROUP_FEATURES = [INPUT_GROUP_INTERACTION_RATE]
TENSOR_GROUP_FEATURES = [INPUT_GROUP_DESCRIPTION]
RAGGED_TECHNIQUE_FEATURES = [
    INPUT_TECHNIQUE_DATA_SOURCES,
    INPUT_TECHNIQUE_DEFENSES_BYPASSED,
    INPUT_TECHNIQUE_DETECTION_NAME,
    INPUT_TECHNIQUE_MITIGATION_ID,
    INPUT_TECHNIQUE_PERMISSIONS_REQUIRED,
    INPUT_TECHNIQUE_PLATFORMS,
    INPUT_TECHNIQUE_SOFTWARE_ID,
    INPUT_TECHNIQUE_TACTICS
]
SCALAR_TECHNIQUE_FEATURES = [INPUT_TECHNIQUE_INTERACTION_RATE]
TENSOR_TECHNIQUE_FEATURES = [INPUT_TECHNIQUE_DESCRIPTION]